version: "3.8"
services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_PASSWORD: { { POSTGRES_PASSWORD } }
      POSTGRES_USER: { { POSTGRES_USER } }
      POSTGRES_DB: { { POSTGRES_DB } }
    volumes:
      - books-db-data:/var/lib/postgresql/data

  bookstore-backend-authors:
    build:
      context: ./authors
      dockerfile: Dockerfile.prod
    environment:
      PORT: { { BACKEND_AUTHORS_PORT } }
      DB_USER: { { BACKEND_DB_USER } }
      DB_PASSWORD: { { BACKEND_DB_PASSWORD } }
      DB_HOST: { { BACKEND_DB_HOST } }
      DB_PORT: { { BACKEND_DB_PORT } }
      DB_NAME: { { BACKEND_DB_NAME } }
    ports:
      - 8081:8080

  bookstore-backend-books:
    build:
      context: ./books
      dockerfile: Dockerfile.prod
    environment:
      PORT: { { BACKEND_AUTHORS_PORT } }
      DB_USER: { { BACKEND_DB_USER } }
      DB_PASSWORD: { { BACKEND_DB_PASSWORD } }
      DB_HOST: { { BACKEND_DB_HOST } }
      DB_PORT: { { BACKEND_DB_PORT } }
      DB_NAME: { { BACKEND_DB_NAME } }
    ports:
      - 8082:8080

volumes:
  books-db-data:
